
export const endpoints = {
    auth: {
        register: "/auth/register",
        login: "/auth/login",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password",
        logout: "/auth/logout",
        verifyOtp: "/auth/verify-otp",
        resendOtp: "/auth/resend-otp",
        changePassword: "/auth/change-password",
        // Admin endpoints
        adminUsers: "/auth/admin/users",
        promoteUser: (userId: string) => `/auth/admin/users/${userId}/promote`,
        updateUser: (userId: string) => `/auth/admin/users/${userId}`,
        triggerOtp: (userId: string) => `/auth/admin/users/${userId}/otp`,
    },
    events: {
        create: "/events/create",
        update: (id: string) => `/events/${id}`,
        delete: (id: string) => `/events/${id}`,
        list: "/events",
        detail: (id: string) => `/events/${id}`,
    },
    media: {
        create: "/media/create",
        list: "/media",
        videos: "/videos", // Alias for /media
    },
    mediaCategory: {
        list: "/media-category",
        create: "/media-category/create",
        update: (id: string) => `/media-category/${id}`,
        delete: (id: string) => `/media-category/${id}`,
    },
    prayer: {
        create: "/prayer/create",
        list: "/prayer",
    },
    products: {
        create: "/product/create",
        list: "/product",
    },
    orders: {
        list: "/orders", // All orders (admin only)
        cancel: (id: string) => `/orders/${id}/cancel`,
    },
    payments: {
        list: "/admin/payments", // All payments (admin only)
        single: (id: string) => `/admin/payments/${id}`,
        stats: "/admin/payments/stats",
        process: (id: string) => `/admin/payments/${id}/process`,
        refund: (id: string) => `/admin/payments/${id}/refund`,
        cancel: (id: string) => `/admin/payments/${id}/cancel`,
        retry: (id: string) => `/admin/payments/${id}/retry`,
        export: "/admin/payments/export",
        analytics: "/admin/payments/analytics",
        bulkProcess: "/admin/payments/bulk-process",
        bulkRefund: "/admin/payments/bulk-refund",
        syncGateway: (id: string) => `/admin/payments/${id}/sync-gateway`,
        logs: (id: string) => `/admin/payments/${id}/logs`,
        create: "/admin/payments/create",
        update: (id: string) => `/admin/payments/${id}`,
        reconciliation: "/admin/payments/reconciliation"
    },
    donations: {
        list: "/donation", // All donations (admin only)
        single: (id: string) => `/donation/${id}`,
        create: "/donation/create",
        update: (id: string) => `/donation/${id}`,
        delete: (id: string) => `/donation/${id}`,
        stats: "/donation/stats",
        export: "/donation/export",
        analytics: "/donation/analytics",
        bulkUpdate: "/donation/bulk-update",
        refund: (id: string) => `/donation/${id}/refund`,
        taxReceipt: (id: string) => `/donation/${id}/tax-receipt`,
        sendReceipt: (id: string) => `/donation/${id}/send-receipt`,
        bulkTaxReceipts: "/donation/bulk-tax-receipts",
        pauseRecurring: (id: string) => `/donation/${id}/pause-recurring`,
        resumeRecurring: (id: string) => `/donation/${id}/resume-recurring`,
        cancelRecurring: (id: string) => `/donation/${id}/cancel-recurring`,
        campaigns: {
            list: "/donation/campaigns",
            single: (id: string) => `/donation/campaigns/${id}`,
            create: "/donation/campaigns/create",
            update: (id: string) => `/donation/campaigns/${id}`,
            delete: (id: string) => `/donation/campaigns/${id}`,
            analytics: (id: string) => `/donation/campaigns/${id}/analytics`
        },
        donors: {
            list: "/donation/donors",
            single: (id: string) => `/donation/donors/${id}`,
            update: (id: string) => `/donation/donors/${id}`,
            export: "/donation/donors/export"
        }
    },
    groups: {
        adminDelete: (id: string) => `/groups/${id}/admin-delete`,
        getAll: "/groups/discover",
        getById: (id: string) => `/groups/${id}`,
        create: "/groups/create",
        update: (id: string) => `/groups/${id}`,
        delete: (id: string) => `/groups/${id}`,
        bulkDelete: "/groups/bulk-delete",
        members: (id: string) => `/groups/${id}/members`,
        addMember: (id: string) => `/groups/${id}/members`,
        updateMember: (id: string, memberId: string) => `/groups/${id}/members/${memberId}`,
        removeMember: (id: string, memberId: string) => `/groups/${id}/members/${memberId}`,
        bulkAddMembers: (id: string) => `/groups/${id}/members/bulk-add`,
        inviteMembers: (id: string) => `/groups/${id}/members/invite`,
        meetings: (id: string) => `/groups/${id}/meetings`,
        createMeeting: (id: string) => `/groups/${id}/meetings`,
        updateMeeting: (id: string, meetingId: string) => `/groups/${id}/meetings/${meetingId}`,
        deleteMeeting: (id: string, meetingId: string) => `/groups/${id}/meetings/${meetingId}`,
        recordAttendance: (id: string, meetingId: string) => `/groups/${id}/meetings/${meetingId}/attendance`,
        stats: "/groups/stats",
        analytics: (id: string) => `/groups/${id}/analytics`,
        export: (id: string) => `/groups/${id}/export`,
        reports: (id: string) => `/groups/${id}/reports`,
        bulkCommunication: (id: string) => `/groups/${id}/communication`,
        search: "/groups/search",
        popular: "/groups/popular",
        upcomingMeetings: "/groups/meetings/upcoming",
        templates: "/groups/templates",
        createFromTemplate: (templateId: string) => `/groups/templates/${templateId}/create`
    },
    ministries: {
        create: "/ministries",
        update: (id: string) => `/ministries/${id}`,
        delete: (id: string) => `/ministries/${id}`,
        list: "/ministries",
        detail: (id: string) => `/ministries/${id}`,
        // Participant management
        participants: (id: string) => `/ministries/${id}/participants`,
        addParticipant: (id: string) => `/ministries/${id}/participants`,
        updateParticipant: (id: string, participantId: string) => `/ministries/${id}/participants/${participantId}`,
        removeParticipant: (id: string, participantId: string) => `/ministries/${id}/participants/${participantId}`,
        // Resource management
        resources: (id: string) => `/ministries/${id}/resources`,
        addResource: (id: string) => `/ministries/${id}/resources`,
        updateResource: (id: string, resourceId: string) => `/ministries/${id}/resources/${resourceId}`,
        deleteResource: (id: string, resourceId: string) => `/ministries/${id}/resources/${resourceId}`,
        // Activity management
        activities: (id: string) => `/ministries/${id}/activities`,
        createActivity: (id: string) => `/ministries/${id}/activities`,
        // Goals management
        updateGoals: (id: string) => `/ministries/${id}/goals`,
        // Statistics and analytics
        analytics: (id: string) => `/ministries/${id}/analytics`,
        // Reporting
        reports: (id: string) => `/ministries/${id}/reports`,
        export: (id: string) => `/ministries/${id}/export`,
        // Search and discovery
        search: "/ministries/search",
        popular: "/ministries/popular",
        // Bulk operations
        bulkDelete: "/ministries/bulk-delete",
        bulkUpdate: "/ministries/bulk-update"
    },
    bibleStories: {
        create: "/bible-stories",
        list: "/bible-stories",
        detail: (id: string) => `/bible-stories/${id}`,
        update: (id: string) => `/bible-stories/${id}`,
        delete: (id: string) => `/bible-stories/${id}`,
        bulkDelete: "/bible-stories/bulk-delete",
        bulkUpdate: "/bible-stories/bulk-update",
        like: (id: string) => `/bible-stories/${id}/like`,
        unlike: (id: string) => `/bible-stories/${id}/unlike`,
        incrementViews: (id: string) => `/bible-stories/${id}/views`,
        addQuestion: (id: string) => `/bible-stories/${id}/questions`,
        updateQuestion: (storyId: string, questionId: string) => `/bible-stories/${storyId}/questions/${questionId}`,
        deleteQuestion: (storyId: string, questionId: string) => `/bible-stories/${storyId}/questions/${questionId}`,
        addActivity: (id: string) => `/bible-stories/${id}/activities`,
        updateActivity: (storyId: string, activityId: string) => `/bible-stories/${storyId}/activities/${activityId}`,
        deleteActivity: (storyId: string, activityId: string) => `/bible-stories/${storyId}/activities/${activityId}`,
        uploadImage: (id: string) => `/bible-stories/${id}/image`,
        uploadAudio: (id: string) => `/bible-stories/${id}/audio`,
        uploadVideo: (id: string) => `/bible-stories/${id}/video`,
        stats: "/bible-stories/stats",
        analytics: "/bible-stories/analytics",
        search: "/bible-stories/search",
        featured: "/bible-stories/featured",
        popular: "/bible-stories/popular",
        recent: "/bible-stories/recent",
        related: (id: string) => `/bible-stories/${id}/related`,
        byCategory: (category: string) => `/bible-stories/category/${category}`,
        byAgeGroup: (ageGroup: string) => `/bible-stories/age-group/${ageGroup}`,
        byDifficulty: (difficulty: string) => `/bible-stories/difficulty/${difficulty}`,
        export: "/bible-stories/export",
        import: "/bible-stories/import",
        tags: "/bible-stories/tags",
        addTag: (id: string) => `/bible-stories/${id}/tags`,
        removeTag: (id: string) => `/bible-stories/${id}/tags`,
    },
}